name: egg island cycles
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Egg Island Cycles
description: bicycle mechanic and ebike specialist
