name: egg island cycles
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Egg Island Cycles
description: bicycle mechanic and ebike specialist
logo: /assets/img/EggIslandLogo2.png
